/*************
 * TODO
 *************

 * Create a Function subclass, AffineTransform, that automatically collapses
   simple transforms and also prints a better diagnostic with printOn
 * Allow stacks of transforms, and transform stack push/operations (brackets, say)
   * this is implicit at the moment, actually, since transforms are applied whenever one hits an Event or Rule, then the stack is cleared.
   	 * FunctionList looks like it's designed for precisely this.
 */