/*
String.rewrite/Plsys
Prewrite
Quarks.gui
redUniverse LSystem
http://www.digipedia.pl/usenet/thread/11165/26516/
file://localhost/Users/dan/Library/Application%20Support/SuperCollider.35/quarks/NatureToolkit/LSys/Help/LSys.html
PpatRewrite  http://www.dewdrop-world.net/words/blog5.php/2011/05/01/neo-complexity-rhythm-generator file://localhost/Users/dan/Library/Application%20Support/SuperCollider.35/quarks/dewdrop_lib/ddwPatterns/Help/PpatRewrite.html