/*
Checkout the Jitlib Pdef/PLazyEnvir tutorial. It seems to be awesome, and recursive, and not at all JITty

* rename private methods to have the pr prefix
* tests
* circular sequencer
* granular flanger with nice tuning options
* PGM of pitch co-occurence
* work out why FFTDiffmags doesn't diff nicely.
* merge mixerchannelpso in to make the psynth thing be a little more friendly
* consolidate the swam and GA animations trees and tidy up the terminology accordingly

*/