/*
Checkout the Jitlib Pdef/PLazyEnvir tutorial. It seems to be awesome, and recursive, and not at all JITty

* tests
* circular sequencer
* granular flanger with nice tuning options
* PGM of pitch co-occurence
* change init methods to use a naming convention that includes the class name
* Generalise to Gerzon m-dimensional allpass 
  * https://en.wikipedia.org/wiki/Unitary_operator
  * https://ccrma.stanford.edu/~jos/pasp/Gerzon_Nested_MIMO_Allpass.html
*
*/